excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://nicomedinap.github.io
title: ProgTon
tagline: A log of everyday life
description: El blog de un astr√≥nomo aburrido
paginate: 5
theme: jekyll-theme-cayman
