excerpt_separator: ""
pygments: ""
url: http://nicomedinap.github.io
title: Fot√≥metro
tagline: Interpretando luz de las estrellas
description: ""
paginate: 10
theme: jekyll-theme-cayman
highlighter: rouge
